services:
  uptime-kuma:
    build:
      context: .
      dockerfile: Dockerfile.simple
    volumes:
      - ./data:/app/data
    ports:
      # <Host Port>:<Container Port>
      - 3001:3001
    restart: unless-stopped
